image: continuumio/miniconda3

options:
  docker: true

pipelines:
  default:

    - step:
        name: Build environment and run tests
        caches:
          - docker
          - pip
        services:
          - docker
          - graph

        script:
          - conda env create -f config/environment.yml
          - source activate bathysphere_graph
          - pytest

    - step:
        name: Build docker image
        caches:
          - docker
        script:
          - pip install docker-compose
          - docker-compose build bathysphere-graph

    - step:
        name: Deploy to Digital Ocean
        deployment: production
        trigger: manual
        script:
          - cat /src/deploy.sh | ssh -t $USERNAME@$BATHYSPHERE_GRAPH

definitions:
  services:
    graph:
      image: neo4j:3.5
      environment:
        NEO4J_AUTH: "neo4j/n0t_passw0rd"
        NEO4J_dbms_memory_pagecache_size: "200M"
        NEO4J_dbms_memory_heap_maxSize: "500M"
      volumes: /data/testing:/data/databases
      healthcheck:
        test: ["CMD", "curl", "-f", "localhost:7474"]
        interval: 30s
        timeout: 5s
        retries: 3