image: continuumio/miniconda3

options:
  docker: true

pipelines:
  default:
    - step:
        name: Install dependencies, unit test, and deploy a local node
        caches:
          - docker
          - pip

        script:
          - pip install docker-compose
          - conda env create -f config/environment.yml
          - source activate bathysphere_graph
          - docker pull neo4j:3.5
          - docker-compose up -d neo4j
          - count=0; retries=10; timeout=6; status="undefined"
          - while [ "$status" != *"healthy"* ]; do
          -   if [ ${count} -gt ${retries} ]; then
          -     echo "Neo4j status is ${status}, aborting"
          -     docker-compose down; exit 1
          -   fi
          -   echo "Neo4j status is ${status}, waiting 5 seconds"
          -   let "count++"; sleep ${timeout}
          -   status=$(docker inspect --format='{{json .State.Health.Status}}' bathysphere-graph_neo4j_1)
          - done
          - echo "Neo4j status is ${status}, continuing with tests"; pytest
          - docker-compose down

    - step:
        name: Build docker image in docker
        caches:
          - docker
        script:
          - pip install docker-compose
          - docker-compose up -d --build
          - docker-compose down

