image: ubuntu:19.04

options:
  docker: true

pipelines:
  default:

    - step:
        name: Build and Push Docker Images
        caches:
          - docker
          - apt
          - pip
        services:
          - docker
        script:
          - rm /etc/apt/apt.conf.d/docker-clean
          - apt update && apt install -y python3-pip
          - pip3 install -r config/bathysphere-graph-env.txt
          - echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          - pip3 install docker-compose
          - docker-compose build neo4j
          - docker-compose push neo4j
          - docker-compose build bathysphere-graph
          - docker-compose push bathysphere-graph

    - step:
        name: Manual deploy to Digital Ocean
        deployment: production
        trigger: manual
        script:
          - echo "cat src/docker-compose-deploy.sh | ssh -t $USERNAME@$BATHYSPHERE_GRAPH"

definitions:
  caches:
    apt: /var/cache/apt/archives