image: ubuntu

options:
  docker: true

pipelines:
  default:

    - step:
        name: Build environment and run tests in VM
        caches:
          - docker
          - pip
        services:
          - docker
        script:
          - apt-get install -y python3-pip
          - pip install -r config/requirements.txt

    - step:
        name: Build database image
        caches:
          - docker
          - pip
        services:
          - docker
        script:
          - echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          - pip install docker-compose
          - docker-compose build neo4j
          - docker-compose push neo4j

#    - step:
#        name: Build API image and run pytest entrypoint
#        caches:
#          - docker
#          - pip
#        services:
#          - docker
#        script:
#          - pip install docker-compose
#          - docker-compose build bathysphere-graph
#          - docker-compose push neo4j

    - step:
        name: Manual deploy to Digital Ocean
        deployment: production
        trigger: manual
        script:
          - echo "cat src/docker-compose-deploy.sh | ssh -t $USERNAME@$BATHYSPHERE_GRAPH"
