image: continuumio/miniconda3

options:
  docker: true

pipelines:
  default:

#    - step:
#        name: Decryption attempt
#        script:
#          - apt-get update && apt-get install -y gpg apt-transport-https
#          - echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | tee -a /etc/apt/sources.list
#          - wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | apt-key add -
#          - apt-get update && apt-get install -y git-secret
#          - echo -e $BATHYSPHERE_GPG_KEY | gpg --import --batch --homedir=.gitsecret/keys
#          - git secret reveal

    - step:
        name: Build environment and run tests in VM
        caches:
          - docker
          - pip
        services:
          - docker
        script:
          - pip install docker-compose
          - conda env create -f config/environment.yml
          - docker pull neo4j:3.5
          - touch config/graph.env
          - docker-compose up -d neo4j
          - source activate bathysphere_graph
          - sleep 5
          - pytest -sv

    - step:
        name: Build docker image and run pytest entrypoint
        caches:
          - docker
          - pip
        services:
          - docker
        script:
          - pip install docker-compose
          - docker-compose build bathysphere-graph
          - docker-compose run --entrypoint="./src/pytest.sh" bathysphere-graph

    - step:
        name: Manual deploy to Digital Ocean
        deployment: production
        trigger: manual
        script:
          - cat src/deploy.sh | ssh -t $USERNAME@$BATHYSPHERE_GRAPH