image: continuumio/miniconda3

options:
  docker: true

pipelines:
  default:

    - step:
        name: Decryption attempt
        script:
          - echo -e $BATHYSPHERE_GPG_KEY > PRIVATE_GPG_KEY.asc
          - echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
          - wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
          - apt-get update && sudo apt-get install gpg git-secret
          - gpg --import PRIVATE_GPG_KEY.asc
          - git secret reveal

    - step:
        name: Build environment and run tests in VM
        caches:
          - docker
          - pip
        services:
          - docker
        script:
          - pip install docker-compose
          - conda env create -f config/environment.yml
          - docker pull neo4j:3.5
          - docker-compose up -d neo4j
          - sh src/pytest.sh

    - step:
        name: Build docker image and run pytest entrypoint
        caches:
          - docker
          - pip
        services:
          - docker
        script:
          - pip install docker-compose
          - docker-compose build bathysphere-graph
          - docker-compose run --entrypoint="./src/pytest.sh" bathysphere-graph

    - step:
        name: Manual deploy to Digital Ocean
        deployment: production
        trigger: manual
        script:
          - cat src/deploy.sh | ssh -t $USERNAME@$BATHYSPHERE_GRAPH