image: continuumio/miniconda3

options:
  docker: true

pipelines:
  default:

    - step:
        name: Build environment and run tests in VM
        caches:
          - docker
          - pip
        services:
          - docker
          - neo4j
        script:
          - conda env create -f config/environment.yml
          - source activate bathysphere_graph
          - pytest

    - step:
        name: Build docker image and run pytest entrypoint
        caches:
          - docker
          - pip
        services:
          - docker
          - neo4j
        script:
          - pip install docker-compose
          - docker-compose build bathysphere-graph
          - docker-compose run --entrypoint="./src/pytest.sh" --no-deps bathysphere-graph

    - step:
        name: Manual deploy to Digital Ocean
        deployment: production
        trigger: manual
        script:
          - cat src/deploy.sh | ssh -t $USERNAME@$BATHYSPHERE_GRAPH

definitions:
  services:
    neo4j:
      image: neo4j:3.5
      environment:
        NEO4J_dbms_memory_pagecache_size: "200M"
        NEO4J_dbms_memory_heap_maxSize: "500M"