version: "3.6"

networks:

  bathysphere:
    driver: bridge

services:

  bathysphere:
    build:
      context: .
      dockerfile: Dockerfile
    image: oceanicsdotio/bathysphere
    ports:
      - 8080:8080
    networks:
      - bathysphere
    environment:
      - NEO4J_HOSTNAME=bathysphere_neo4j_1  # replaces localhost in Docker networking setup
      - NEO4J_ACCESS_KEY=n0t_passw0rd  # must match value declared in neo4j image below
      - PORT=8080
    volumes:
      - ./logs:/logs
    depends_on: 
      - neo4j
    
  neo4j:
    image: neo4j:4.2.5
    ports:
      - 7474:7474 # http
      - 7473:7473 # https
      - 7687:7687 # bolt
    # volumes:
    #   - ./data/neo4j/:/data
    #   - ./logs/neo4j/:/logs
    #   - ./data/import:/var/lib/neo4j/import
    networks:
      - bathysphere
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_AUTH=neo4j/n0t_passw0rd
  
  bivalve:
    build: 
      context: .
      dockerfile: bivalve.Dockerfile
    image: oceanicsdotio/bivalve
    environment:
      - BIVALVE_DLL
      - SPACES_ACCESS_KEY
      - SPACES_SECRET
      - STORAGE_ENDPOINT
      - BUCKET_NAME=oceanicsdotio
      - SERVICE_NAME=bivalve
      - PORT=5000
    ports:
      - 5000:5000
    networks:
      - bathysphere