version: "3.6"

networks:

  bathysphere:
    driver: bridge

services:

  bathysphere:
    build:
      context: .
    image: oceanicsdotio/bathysphere
    ports:
      - 5000:5000
    networks:
      - bathysphere
    environment:
      - NEO4J_HOSTNAME=bathysphere_neo4j_1  # replaces localhost in Docker networking setup
      - NEO4J_ACCESS_KEY=n0t_passw0rd  # must match value declared in neo4j image below
    volumes:
      - ./logs:/logs
    depends_on: 
      - neo4j
      - redis
    
  neo4j:
    image: neo4j:3.5.16  # TODO: bump to 4.0 when there is graphql support
    ports:
      - 7474:7474 # http
      - 7473:7473 # https
      - 7687:7687 # bolt
    volumes:
      - ./data/neo4j/:/data
      - ./logs/neo4j/:/logs
      - ./data/import:/var/lib/neo4j/import
    networks:
      - bathysphere
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_dbmd_security_auth__enabled=true
    #   - NEO4J_dbms_security_http__access__control__allow__origin=http://localhost:8000
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_AUTH=neo4j/n0t_passw0rd
      - NEO4J_browser_remote__content__hostname__whitelist=localhost,https://graph.oceanics.io
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G

      
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - bathysphere
    depends_on:
      - neo4j
