version: "3.6"

networks:

  bathysphere:
    driver: bridge

services:

  bathysphere:
    build:
      context: .
    image: oceanicsdotio/bathysphere
    ports:
      - 5000:5000
    networks:
      - bathysphere
    volumes:
      - ./logs:/logs
    depends_on: 
      - neo4j
      - redis
    
  neo4j:
    image: neo4j:4.0
    # build:
    #   context: .
    #   dockerfile: config/neo4j-dockerfile
    # image: oceanicsdotio/neo4j
    ports:
      - 7474:7474 # http
      - 7473:7473 # https
      - 7687:7687 # bolt
    volumes:
      - ./data/neo4j/:/data
      - ./logs/neo4j/:/logs
      - ./data/import:/var/lib/neo4j/import
    networks:
      - bathysphere
    environment: 
      - NEO4J_AUTH=neo4j/n0t_passw0rd
      - NEO4J_browser_remote__content__hostname__whitelist=localhost,https://graph.oceanics.io
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G

      
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - bathysphere
    depends_on:
      - neo4j
