version: "3"

networks:
  oceanics:
    driver: bridge

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./openapi:/openapi
    depends_on:
      - neo4j
      - bathysphere-graph
    networks:
      - oceanics
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3

  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474 # HTTP
      - 7473:7473 # HTTPS
      - 7687:7687 # BOLT
    environment:
      - NEO4J_AUTH=neo4j/n0t_passw0rd
      - NEO4J_dbms_memory_pagecache_size=200M
      - NEO4J_dbms_memory_heap_maxSize=500M
    volumes:
      - ${GRAPHDB/graph:-./data/testing}:/data/databases
      - ${GRAPHDB/logs:-./logs}:/logs
      - ${GRAPHDB/import:-./data/import}:/var/lib/neo4j/import
    networks:
      - oceanics
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:7474"]
      interval: 30s
      timeout: 5s
      retries: 3


  bathysphere-graph:
    build: .
    image: oceanicsdotio/bathysphere-graph
    ports:
      - 5000:5000
    networks:
      - oceanics
    volumes:
      - ./src:/src
      - ./logs:/logs
    depends_on:
      - neo4j
