version: "3"

networks:
  oceanics:
    driver: bridge

services:

  reverseproxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./openapi:/openapi
#    depends_on:
#      - neritics-ml
    networks:
      - oceanics

  neritics-ml:
    build: .
    image: oceanicsdotio/neritics-ml
    ports:
      - 5000:5000
    networks:
      - oceanics
