version: "3.4"

networks:
  oceanics:
    driver: bridge

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./openapi:/openapi
    depends_on:
      - neo4j
      - bathysphere-graph
    networks:
      - oceanics
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:443"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474 # HTTP
      - 7473:7473 # HTTPS
      - 7687:7687 # BOLT
    environment:
      - NEO4J_dbms_security_auth_max_failed_attempts=6
      - NEO4J_dbms_memory_pagecache_size=200M
      - NEO4J_dbms_memory_heap_maxSize=500M
    volumes:
      - ${GRAPHDB:-./data/neo4j}:/data
      - ./logs/neo4j/:/logs
      - ./data/import:/var/lib/neo4j/import
    networks:
      - oceanics
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:7474"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  bathysphere-graph:
    build: .
    image: oceanicsdotio/bathysphere-graph
    ports:
      - 5000:5000
    env_file:
         - ./Docker/api/api.env
    networks:
      - oceanics
    volumes:
      - ./src:/src
      - ./logs:/logs
    depends_on:
      - neo4j
