name: filter
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - matplotlib
  - tensorflow
  - pip:
    - connexion
    - flask
    - gunicorn
    - flask_cors
    - requests
    - redis