[build]
publish = "openapi"

[[redirects]]
  from = "/docs"
  to = "/docs/bathysphere"
  status = 301
  force = false

[[redirects]]
  from = "/api/*"
  to = "https://bathysphere-f6ccuy4zzq-uc.a.run.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}