[build]
  base = "/"
  command = "make build"
  publish = "public"
  functions = "/functions"
  environment = {GO_VERSION = "1.14.6", NODE_VERSION = "12", AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"}

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/mesh-nodes/*"
  to = "oceanicsdotio.cdn.nyc3.digitaloceanspaces.com"
  status = 303

[[redirects]]
  from = "/bathysphere"
  to = "/bathysphere/index.html"
  status = 301
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = '''
        *.oceanics.io,
        *.googleapis.com,
        *.github.com,
        cdn.jsdelivr.net
    '''
