[build]
  base = "/"
  publish = "out"
  command = "yarn next build"
  functions = "functions/src"

[build.environment]
  NODE_VERSION = "21"
  AWS_LAMBDA_JS_RUNTIME = "nodejs21.x"
  UV_THREADPOOL_SIZE = 16
  NETLIFY_NEXT_PLUGIN_SKIP = true

[dev]
  port = 8888
  framework = "#static"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  
[functions]  
  node_bundler = "esbuild"
  included_files = [
    "specification.json",
  ]
  external_node_modules = [
    "@oceanics/functions",
    "neo4j-driver"
  ]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  headers = {X-From = "Netlify"}

# [[redirects]]
#   from = "/catalog/*" 
#   to = "/"
#   status = 401
#   force = true

[[redirects]]
  from = "/compute/*" 
  to = "/"
  status = 401
  force = true

[[redirects]]
  from = "/read/*" 
  to = "/"
  status = 401
  force = true
