[build]
  base = "/"
  publish = "/oceanics-io-www/build"
  functions = "/functions/src"
  command = "make ."

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  NETLIFY_USE_YARN = "true"
  NETLIFY_YARN_WORKSPACES = "true"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"

[dev]
  port = 8888
  framework = "#static"

[functions]  
  node_bundler = "esbuild"

