[build]
  base = "/"
  publish = "/build"
  command = "make ."

[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"

[dev]
  port = 8888
  framework = "#static"
