[build]
  base ="/"
  command = "make build"
  publish = "public"
  functions = "/functions"

[build.environment]
  GO_VERSION = "1.14.6"

[[redirects]]
  from = "/catalog"
  to = "/app"
  force = true

[[redirects]]
  from = "/vessel"
  to = "/app"
  force = true

[[redirects]]
  from = "/map"
  to = "/app"
  force = true

[[redirects]]
  from = "/oceanside"
  to = "/app"
  force = true

[[redirects]]
  from = "/turbulence-demo"
  to = "/app"
  force = true

[[redirects]]
  from = "/legal"
  to = "/policy"
  force = true


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[plugins]]
  package = "netlify-plugin-gatsby-cache"
