[build]
  base ="/"
  command = "make build"
  publish = "public"
  functions = "functions"

[build.environment]
  GO_VERSION = "1.14.6"

[[redirects]]
  from = "/catalog"
  to = "/app"

[[redirects]]
  from = "/vessel"
  to = "/app"

[[redirects]]
  from = "/map"
  to = "/app"

[[redirects]]
  from = "/oceanside"
  to = "/app"

[[redirects]]
  from = "/turbulence-demo"
  to = "/app"

[[redirects]]
  from = "/legal"
  to = "/policy"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
