[build]
  base = "dummy/"
  publish = "../build"
  command = "cd ../ & make ."
  ignore = "exit 1"

[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"

[dev]
  port = 8888
  framework = "#static"
