[build]
  base ="/"
  command = "make build"
  publish = "public"
  functions = "functions"

[build.environment]
  GO_VERSION = "1.14.6"

[[redirects]]
  from = "/catalog/*"
  to = "/catalog.html"
  status = 200
