[build]
  base = "/"
  publish = "/oceanics-io-www/build"
  functions = "/oceanics-io-api/build"
  command = "make ."
  environment = {NODE_VERSION = "16", AWS_LAMBDA_JS_RUNTIME = "nodejs16.x", NETLIFY_USE_YARN = "true", NETLIFY_YARN_WORKSPACES = "true", YARN_VERSION="1.22.17"}
  
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/:left/:right"
  to = "/.netlify/functions/topology"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/Things"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/Sensors"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/ObservedProperties"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/Observations"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/Locations"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/HistoricalLocations"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/FeaturesOfInterest"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/Actuators"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/Tasks"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/TaskingCapabilties"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/DataStreams"
  to = "/.netlify/functions/collection"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/DataStreams*"
  to = "/.netlify/functions/entity"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/:left"
  to = "/.netlify/functions/entity"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/index"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/functions/:splat"
  to = "/.netlify/functions/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = '''
        *.oceanics.io,
        *.googleapis.com,
        *.github.com,
        cdn.jsdelivr.net
    '''
