[build]
  base = "/"
  publish = "/oceanics-io-www/build"
  functions = "/oceanics-io-api/src"
  edge_functions = "/oceanics-io-api/edge"
  command = "make ."

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  NETLIFY_USE_YARN = "true"
  NETLIFY_YARN_WORKSPACES = "true"
  YARN_VERSION="1.22.17"

[[plugins]]
  # https://www.netlify.com/blog/general-availability-content-security-policy-csp-nonce-integration/ 
  package = "@netlify/plugin-csp-nonce"

[dev]
  port = 8888
  framework = "#static"

[[edge_functions]]
  path = "/api*"
  function = "rewrite"

[functions]  
  node_bundler = "esbuild"
  included_files = ["oceanics-io-api/src/shared/bathysphere.json"]
 
[functions.auth]
  external_node_modules = ["oceanics-io-api-wasm"]

[functions.collection]
  external_node_modules = ["oceanics-io-api-wasm"]

[functions.entity]
  external_node_modules = ["oceanics-io-api-wasm"]

[functions.index]
  external_node_modules = ["oceanics-io-api-wasm"]

[functions.topology]
  external_node_modules = ["oceanics-io-api-wasm"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

    
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  headers = {X-From = "Netlify"}

[functions.content]
  external_node_modules = ["oceanics-io-api-wasm"]

