version: 1.0

provider:
  name: bathysphere_functions
  gateway: http://127.0.0.1:8080

functions:

  buoy:
    lang: python3-http
    handler: ./bathysphere_functions_buoy
    image: bathysphere/bathysphere_functions_buoy-function:latest
    environment:
      hostname: maine.loboviz.com
    secrets:
      - payload-secret

#  controller:
#    lang: python3
#    handler: ./controller
#    image: bathysphere/faas-contoller:latest
#
#
#  archive:
#    lang: python3
#    handler: ./archive
#    environment:
#      hostname: maine.loboviz.com
#    image: bathysphere/faas-archive:latest
#    secrets:
#      - loboviz-admin
#      - loboviz-secret
#
#  parse:
#    lang: python3
#    handler: ./parse
#    image: bathysphere/faas-parse:latest
#
#  notify:
#    lang: python3
#    handler: ./notify
#    image: bathysphere/notify-function:latest
#    secrets:
#      - mail-service-key
#      - smtp-host
#      - payload-secret
#
#  postgres:
#    lang: python3
#    handler: ./postgres
#    image: bathysphere/postgres-function:latest
#    secrets:
#      - payload-secret
#      - pg-username
#      - pg-hostname
#      - pg-password
#      - pg-port
#
#  cache:
#    lang: python3
#    handler: ./cache
#    image: bathysphere/cache-function:latest
#    secrets:
#      - payload-secret
#      - redis-host
#      - redis-key
#      - redis-port

#  repository:
#    lang: python3
#    handler: ./repository
#    image: repository:latest
#    secrets:
#      - object-storage