[build]
  command = "make build"
  publish = "public"
  functions = "/functions"
  environment = {NODE_VERSION = "12", AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"}

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/mesh-nodes/*"
  to = "oceanicsdotio.cdn.nyc3.digitaloceanspaces.com"
  status = 303
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = '''
        *.oceanics.io,
        *.googleapis.com,
        *.github.com,
        cdn.jsdelivr.net
    '''
