shell: 
  cavity_water_correction: 1.115
  energy_content: 0.161
  water_content: 0.189
  length:
    coefficient: 2.767
    exponent: 0.327
    maturation: 5.0

tissue:
  water_content: 0.914
  mean_allocation: 0.76
  proportion_dry_loss_to_spawn: 0.44

thermodynamics:
  heat_loss_coefficient: 0.067
  spawning_threshold: 19.0
        
           
ammonium_excretion: 
  max: 1350.0
