metadata:
  name: "test-configuration"
  description: "A test configuration"
  keywords:
    - test
    - shellfish
  license: "No restrictions"

properties:
  workers: 2
  dt: 3600
  integration: "euler"
  backend: "ensemble"