[package]
name = "bathysphere"
version = "2.0.0"
authors = ["Oceanicsdotio <business@oceanics.io>"]
edition = "2018"

[lib]
name = "bathysphere"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
