[package]
name = "bathysphere"
version = "0.1.0"

[lib]
name = "bathysphere"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.0.2"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]