time_series_scatter_plot: 
  view: series
  artifact: test_capsize_datastream_scatter_plot
  extent: [0, 365, 0, 10]
  data: 
    points: 
      shape: [365, 10]
  style: 
    base: dark 
    alpha: 0.5 
    marker: 5
  
  args: 
    unwind: False 
    labels: [a]


time_series_frequency: 
  view: frequency
  artifact: test_capsize_datastream_frequency
  data: 
    points:
      shape: [365, 100]
  style: 
    base: dark 
    alpha: 0.5 
    marker: 5
    

time_series_coverage: 
  view: coverage
  artifact: test_capsize_datastream_coverage
  data: 
    points:
      shape: [365, 1000]
  style: 
    base: dark 
    alpha: 0.5 
    marker: 5
