environment:
  ADMIN: ""
  NEO4J_AUTH: neo4j/neo4j
  ADMIN_PASS: ""
  API_KEY: ""
  HOST: localhost
  EMAIL_ACCT:
  EMAIL_KEY:
  EMAIL_SERVER:
  EMAIL_PORT:
  REPLY_TO:
  SECRET:
  PORT: 5000
  BASE_PATH: /api
  SPEC_PATH: ../openapi/
  DOCKER_COMPOSE_NAME: bathysphere-graph_neo4j_1
  DOCKER_CONTAINER_NAME: neo4j
  EMBEDDED_NAME: localhost
  RETRIES: 3
  DELAY: 10
  NEO4J_PORT: 7687
  NEO4J_HOST:
  DARKSKY_API_KEY: ""
  MAX_CALLS: 1000
  PG_USERNAME:
  PG_PASSWORD:
  PG_DATABASE:
  PG_HOST:
  PG_PORT:
  REDIS_KEY:
  REDIS_HOST: bathysphere-redis-do-user-3962990-0.db.ondigitalocean.com
  LOBOVIZ_USER:
  LOBOVIZ_PASSWORD:
  storageAccessKey:
  storageSecretKey:


specPath: "openapi/api.yml"
basePath: "/api"
enableSwagger: false
lock: "lock.json"
index: "index.json"


bucketName: "oceanicsdotio"
storageLocalCache: "data/"
storage:
  endpoint: "nyc3.digitaloceanspaces.com"
  secure: true

headers:
  x-amz-acl: "public-read"
  x-amz-meta-service: "bathysphere"


models:

  base:
    - User
    - Ingress
    - Catalogs
    - Collections
    - Items

  sensing:
    - Things
    - Datastreams
    - Observations
    - ObservedProperties
    - HistoricalLocations
    - Locations
    - Sensors
    - FeaturesOfInterest

  tasking:
    - Actuators
    - TaskingCapabilities
    - Tasks

Ingresses:
  - name: Oceanicsdotio
    owner: true
    description: Research and development
    url: oceanics.io

  - name: Public
    description: Public Data Repository
    apiKey: ""

  - name: University of Maine
    description: Aquaculture research partner
    url: maine.edu

  - name: Cabot7
    description: Fisheries data partner
    url: cabot7.com


FeaturesOfInterest:
  - name: Damariscotta River Estuary shellfish growing area
    description: |
      The Damariscotta River Estuary is a traditional growing area for oysters in Maine.

  - name: Midcoast Maine Mesh
  - name: Gulf of Maine Mesh
  - name: Damariscotta River Nested Mesh




ObservedProperties:
   - name: Temperature
     description: |
       Temperature as measured through a thermistor or remote sensing
   - name: Chlorophyll
     description: |
       Measure of chlorophyll
   - name: Salinity
     description: |
       Seawater salinity

   - name: cdom
   - name: chlorophyll
   - name: conductivity
   - name: current_direction
   - name: current_speed_cm
   - name: depth
   - name: oxygen
   - name: nitrate
   - name: oxygen_sat
   - name: oxygen_percent
   - name: par0minus
   - name: par0plus
   - name: salinity
   - name: temperature
   - name: transmission
   - name: turbidity
   - name: voltage

Locations:
  - name: Upper Damariscotta Estuary
    description: Buoy deployment
    location: [43.998178, -69.54253, 0.0]

  - location: [-45.0, 36.0, -5.0]
  - location: [-45.01, 36.01, -5.0]

  - name: "Wood Island Harbor"
    location:
      type: Point
      coordinates: [43.456550, -70.344432]

  - name: "Lower Damariscotta"
    location:
      type: Point
      coordinates: [43.93354, -69.58344]

  - name: "Ram Island Saco Bay"
    location:
      type: Point
      coordinates: [43.465934, -70.359646]

  - name: "Upper New Meadows"
    location:
      type: Point
      coordinates: [43.863669, -69.8984055]  # Bombazine / New Meadows

  - name: "Lower New Meadows"
    location:
      type: Point
      coordinates: [43.77643055, -69.89196944]  # Sand Cove / New Meadows

  - name: "Bagaduce River"
    location:
      type: Point
      coordinates: [44.40156667, -68.7738333]

  - name: "Machias Bay"
    location:
      type: Point
      coordinates: [44.618517, -67.318033]

  - name: "Cobscook Bay"
    location:
      type: Point
      coordinates: [44.8968, -67.0651]

  - name: "Western Passage / Passamaquoddy Bay"
    location:
      type: Point
      coordinates: [44.92017, -66.995833]

  - name: "Harpswell Sound"


Sensors:
  - name: SeaBird Electronics CTD
    description: A common oceanographic sensing package

  - name: Chlorophyll fluorometer
    description: For measuring plankton stuff


Things:
  - name: Land Ocean Biogeochemical Observatory
    description: |
      Moored buoy with instrumentation, deployed in the Damariscotta River
      Estuary (Maine) as part of the Sustainable Ecological Aquaculture Network project.
    links:
      Locations:
        - id: 0
          label: Linked

  - name: Regional Sentinel Model Service
    description: |
      Operational model for Maine aquaculture


Datastreams:
  - name: temperature
    description: |
      Just another temperature series
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked
      Sensors:
        - id: 0
          label: Linked
      ObservedProperties:
        - name: temperature
          label: Linked

  - name: cholorophyll
    description: |
      Just another chlorophyll series

    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked

      Sensors:
        - id: 0
          label: Linked

      ObservedProperties:
        - name: chlorophyll
          label: Linked


Observations:
  - ts: 1000.234
    val: 10.0
    links:
      Datastreams:
        - name: temperature
          label: Linked

      FeaturesOfInterest:
        - id: 0
          label: Linked

  - ts: 1002.793
    val: 10.5
    links:
      Datastreams:
        - name: temperature
          label: Linked

      FeaturesOfInterest:
        - id: 0
          label: Linked

  - ts: 1005.208
    val: 10.4
    links:
      Datastreams:
        - name: temperature
          label: Linked

      FeaturesOfInterest:
        - id: 0
          label: Linked

TaskingCapabilities: []

Tasks:
  - taskingParameters:
      location: host:port/endpoint
      message: something

  - taskingParameters:
      location: host:port/endpoint
      message: something-else


Actuators:
  - name: Solenoid
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked

  - name: Solenoid
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked

  - name: Solenoid
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked
