environment:
  ADMIN: ""
  NEO4J_AUTH: neo4j/neo4j
  ADMIN_PASS: ""
  API_KEY: ""
  HOST: localhost
  EMAIL_ACCT:
  EMAIL_KEY:
  EMAIL_SERVER:
  EMAIL_PORT:
  REPLY_TO:
  SECRET:
  PORT: 5000
  BASE_PATH: /api
  SPEC_PATH: ../openapi/
  DOCKER_COMPOSE_NAME: bathysphere-graph_neo4j_1
  DOCKER_CONTAINER_NAME: neo4j
  EMBEDDED_NAME: localhost
  RETRIES: 3
  DELAY: 10
  NEO4J_PORT: 7687
  NEO4J_HOST:


models:

  base:
    - User
    - Ingress
    - Catalogs
    - Collections
    - Items

  sensing:
    - Things
    - Datastreams
    - Observations
    - ObservedProperties
    - HistoricalLocations
    - Locations
    - Sensors
    - FeaturesOfInterest

  tasking:
    - Actuators
    - TaskingCapabilities
    - Tasks

Ingresses:
  - name: Oceanicsdotio
    owner: true
    description: Research and development
    url: oceanics.io

  - name: Public
    description: Public Data Repository
    apiKey: ""

  - name: University of Maine
    description: Aquaculture research partner
    url: maine.edu

  - name: Cabot7
    description: Fisheries data partner
    url: cabot7.com


FeaturesOfInterest:
  - name: Damariscotta River Estuary shellfish growing area
    description: |
      The Damariscotta River Estuary is a traditional growing area for oysters in Maine.

  - name: Midcoast Maine Mesh
  - name: Gulf of Maine Mesh
  - name: Damariscotta River Nested Mesh


ObservedProperties:
   - name: Temperature
     description: |
       Temperature as measured through a thermistor or remote sensing
   - name: Chlorophyll
     description: |
       Measure of chlorophyll
   - name: Salinity
     description: |
       Seawater salinity

Locations:
  - name: Upper Damariscotta Estuary
    description: Buoy deployment
    location: [43.998178, -69.54253, 0.0]

  - location: [-45.0, 36.0, -5.0]
  - location: [-45.01, 36.01, -5.0]

Sensors:
  - name: SeaBird Electronics CTD
    description: A common oceanographic sensing package

  - name: Chlorophyll fluorometer
    description: For measuring plankton stuff


Things:
  - name: Land Ocean Biogeochemical Observatory
    description: |
      Moored buoy with instrumentation, deployed in the Damariscotta River
      Estuary (Maine) as part of the Sustainable Ecological Aquaculture Network project.
    links:
      Locations:
        - id: 0
          label: Linked

  - name: Regional Sentinel Model Service
    description: |
      Operational model for Maine aquaculture


Datastreams:
  - name: temperature
    description: |
      Just another temperature series
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked
      Sensors:
        - id: 0
          label: Linked
      ObservedProperties:
        - name: temperature
          label: Linked

  - name: cholorophyll
    description: |
      Just another chlorophyll series

    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked

      Sensors:
        - id: 0
          label: Linked

      ObservedProperties:
        - name: chlorophyll
          label: Linked


Observations:
  - ts: 1000.234
    val: 10.0
    links:
      Datastreams:
        - name: temperature
          label: Linked

      FeaturesOfInterest:
        - id: 0
          label: Linked

  - ts: 1002.793
    val: 10.5
    links:
      Datastreams:
        - name: temperature
          label: Linked

      FeaturesOfInterest:
        - id: 0
          label: Linked

  - ts: 1005.208
    val: 10.4
    links:
      Datastreams:
        - name: temperature
          label: Linked

      FeaturesOfInterest:
        - id: 0
          label: Linked

TaskingCapabilities: []

Tasks:
  - taskingParameters:
      location: host:port/endpoint
      message: something

  - taskingParameters:
      location: host:port/endpoint
      message: something-else


Actuators:
  - name: Solenoid
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked

  - name: Solenoid
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked

  - name: Solenoid
    links:
      Things:
        - name: Land Ocean Biogeochemical Observatory
          label: Linked
