---
apiVersion: extensions/tasking
kind: Actuators
metadata:
  Things@iot.navigation:
    - name: [ Land Ocean Biogeochemical Observatory ]
spec:
  name: modem power switch
---
apiVersion: extensions/sensing
kind: Datastreams
metadata:
  Things@iot.navigation:
    - name: [ Land Ocean Biogeochemical Observatory ]
  Sensors@iot.navigation:
    - id: [ 0 ]
  ObservedProperties@iot.navigation:
    - name: [ temperature ]
spec:
  name: temperature
  description: Just another temperature series
---
apiVersion: extensions/sensing
kind: Datastreams
metadata:
  Things@iot.navigation:
    - name: [ Land Ocean Biogeochemical Observatory ]
  Sensors@iot.navigation:
    - id: [ 0 ]
  ObservedProperties@iot.navigation:
    - name: [ chlorophyll ]
spec:
  name: chlorophyll
  description: Just another chlorophyll series
---
apiVersion: extensions/sensing
kind: FeaturesOfInterest
spec:
  name: Damariscotta River Estuary shellfish growing area
  description: Traditional growing area for oysters in Maine.
---
apiVersion: extensions/sensing
kind: FeaturesOfInterest
spec:
  name: Midcoast Maine Mesh
---
apiVersion: extensions/sensing
kind: FeaturesOfInterest
spec:
  name: Gulf of Maine Mesh
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 65
spec:
  name: Lower Damariscotta
  location:
    type: Point
    coordinates: [43.93354, -69.58344]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 66
spec:
  name: Upper Damariscotta Estuary
  description: Buoy deployment
  location:
    type: Point
    coordinates: [ 43.998178, -69.54253, 0.0 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 64
spec:
  name: Wood Island Harbor
  location:
    type: Point
    coordinates: [ 43.456550, -70.344432 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 67
spec:
  name: Ram Island Saco Bay
  location:
    type: Point
    coordinates: [ 43.465934, -70.359646 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 70
spec:
  name: Upper New Meadows
  location:
    type: Point
    coordinates: [ 43.863669, -69.8984055 ]  # Bombazine / New Meadows
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 71
spec:
  name: Lower New Meadows
  location:
    type: Point
    coordinates: [ 43.77643055, -69.89196944 ]  # Sand Cove / New Meadows
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 72
spec:
  name: Bagaduce River
  location:
    type: Point
    coordinates: [ 44.40156667, -68.7738333 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 73
spec:
  name: Machias Bay
  location:
    type: Point
    coordinates: [ 44.618517, -67.318033 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 74
spec:
  name: Cobscook Bay
  location:
    type: Point
    coordinates: [ 44.8968, -67.0651 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 75

  Ingresses@iot.navigation:
    - label: Alias
      props:
        name: [ Passamaquoddy Bay ]
spec:
  name: Western Passage
  location:
    type: Point
    coordinates: [ 44.92017, -66.995833 ]
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Things@iot.navigation:
    - name: [ loboviz ]
      props:
        node: 52
spec:
  name: Harpswell Sound
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - name: [ NOAA ]
  Assets@iot.navigation:
    - name:
      - 20170709140704-NCEI-L3C_GHRSST-SSTskin-AVHRR_Pathfinder-PFV5.3_NOAA19_G_2017190_day-v02.0-fv01.0.nc
spec:
  name: National Oceanography Data Center
  location:
    type: Network
    protocol: https
    host: data.nodc.noaa.gov
    port: 80
    service: "/thredds/dodsC/pathfinder/Version5.3/L3C/{}/data/{}"
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ maine.edu, loboviz.com ]
spec:
  name: Maine Loboviz Data
  location:
    type: Network
    protocol: http
    host: maine.loboviz.com
    port: 80
    service: cgi-data/nph-data.cgi
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ maine.edu, loboviz.com ]
spec:
  name: Maine Loboviz Archive
  location:
    type: Network
    protocol: http
    host: maine.loboviz.com
    port: 80
    service: bathysphere_functions_archive
  auth:
    basic:
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ maine.edu, loboviz.com ]
spec:
  name: Maine Loboviz Sensor Metadata
  location:
    type: Network
    protocol: http
    host: maine.loboviz.com
    port: 80
    service: bathysphere_functions_archive
  auth:
    basic:
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ maine.edu ]
  Assets@iot.navigation:
    - name: [ LC8011030JulyAvLGN00_OSI.nc ]
      onCreate:
        format: netcdf
    - name: [ LC08_L1TP_011030_20170709_20170717_01_T1_B10.tif ]
      onCreate:
        format: geotiff
spec:
  name: University of Maine Satellite Data
  location:
    type: Network
    protocol: ftp
    host: misclab.umeoce.maine.edu
    port: 80
    service: users/misclab/coastal_sat
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ bowdoin.edu, loboviz.com ]
spec:
  name: Bowdoin Loboviz Data
  location:
    type: Network
    protocol: http
    host: bowdoin.loboviz.com
    port: 80
    service: cgi-data/nph-data.cgi
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ umassd.edu ]
  Assets@iot.navigation:
    - name: [ "gom3_{}.nc" ]
      format: netcdf
spec:
  name: NECOFS data
  location:
    type: Network
    protocol: http
    host: www.smast.umassd.edu
    port: 8080
    service: thredds/dodsC/models/fvcom/NECOFS/Archive/Seaplan_33_Hindcast_v1
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ oceanics.io ]
      props:
        bucketName: oceanicsdotio
        lockFile: lock.json
        indexFile: index.json
spec:
  name: Object Storage
  location:
    type: Network
    protocol: https
    host: nyc3.digitaloceanspaces.com
    port:
    connection:
      retries: 3
      delay: 1
    auth:
      basic:
    headers:
      x-amz-acl: private
      x-amz-meta-service: bathysphere
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - name: [ Public ]
      props:
        bucketName: oceanicsdotio
        readOnly: true
spec:
  name: Object Storage
  location:
    type: Network
    protocol: https
    host: nyc3.digitaloceanspaces.com
    port:
    connection:
      retries: 3
      delay: 1
    headers:
      x-amz-acl: public-read
      x-amz-meta-service: bathysphere
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ oceanics.io ]
      props:
        database: bathysphere
spec:
  name: Spatiotemporal Database
  location:
    type: Network
    protocol: https
    host:
    port:
    connection:
      retries: 3
      delay: 1
    auth:
      basic:
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ oceanics.io ]
spec:
  name: API Cache
  location:
    type: Network
    protocol: https
    host:
    port:
    connection:
      retries: 3
      delay: 1
    auth:
      apiKey:
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ oceanics.io ]
spec:
  name: neo4j-local
  location:
    type: Network
    protocol: bolt
    host: localhost
    port: 7687
    connection:
      retries: 3
      delay: 1
    auth:
      basic: neo4j/neo4j
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Ingresses@iot.navigation:
    - domain: [ darksky.com ]
      props:
        maxCalls: 1000
spec:
  name: weather-service
  location:
    type: Network
    protocol: https
    host: darksky.com
    port: 80
    auth:
      apiKey:
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  Providers@iot.navigation:
    - domain: [ oceanics.io ]
  config:
     specification: ../openapi/
     logging: "logs/{}"
     basePath: "/api"
     specPath: "openapi/api.yml"
     healthcheck: "http://{}/api/Things"
     image:      
      styles:
        base:
            padding: [0.1, 0.2, 0.05, 0.1]
            marker: 1
            font: 10
            text: 10
            width: 6.5
            height: 4.0
            line: 1.0
            alpha: 1.0
            dpi: 150
            legend: false
            grid: false
            imageInterp: bilinear
        
        dark:
            bg: black
            contrast: white
            flag: red
            label: white
            colors: [purple, blue, red, grey, green, yellow, orange, brown]
        
        light:
            bg: white
            contrast: black
            flag: red
            label: black
            colors: [purple, blue, red, grey, green, yellow, orange, brown]
        
spec:
  name: bathysphere-api
  location:
    type: Network
    protocol: https
    host: graph.oceanics.io
    service: /api
    port: 80
    auth:
      apiKey:
      basic:
---
apiVersion: extensions/sensing
kind: Locations
metadata:
  config:
     specification: ../openapi/
     enableSwagger: false
  Providers@iot.navigation:
    - domain: [ oceanics.io ]
spec:
  name: bathysphere-api-proxy
  location:
    type: Network
    protocol: http
    host: localhost
    service: /api
    port: 5000
    auth:
      apiKey:
      basic:
---
apiVersion: extensions/sensing
kind: Observations
metadata:
  Datastreams@iot.navigation:
    - name: [ temperature ]
  FeaturesOfInterest@iot.navigation:
    - id: [ 0 ]
spec:
  ts: 1000.234
  val: 10.0
---
apiVersion: extensions/sensing
kind: Observations
metadata:
  Datastreams@iot.navigation:
    - name: [ temperature ]
  FeaturesOfInterest@iot.navigation:
    - id: [ 0 ]
spec:
  ts: 1100.194
  val: 11.7
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  Providers@iot.navigation:
    - label: Alias
      props:
        name: [ temp ]
spec:
  name: temperature
  description: Measured through a thermistor or remote sensing
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  Providers@iot.navigation:
    - label: Alias
      props:
        name: [ chl, chla, chl-a ]
spec:
  name: chlorophyll
  description: Measure of chlorophyll
---
apiVersion: extensions/sensing
kind: ObservedProperties
spec:
  name: conductivity
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  ObservedProperties@iot.navigation:
    - name: [ conductivity ]
  Providers@iot.navigation:
    - label: Alias
      props:
        name: [ psu, sss, sal ]
spec:
  name: salinity
  description: Seawater salinity
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  ObservedProperties@iot.navigation:
    - name: [ chlorophyll ]
  Providers@iot.navigation:
    - label: Alias
      props:
        name: [ cdom ]
spec:
  name: colored dissolved organic matter
---
apiVersion: extensions/sensing
kind: ObservedProperties
spec:
  name: oxygen
---
apiVersion: extensions/sensing
kind: ObservedProperties
spec:
  name: oxygen saturation
---
apiVersion: extensions/sensing
kind: ObservedProperties
spec:
  name: oxygen percent
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  Providers@iot.navigation:
    - label: Alias
      props:
         name: [ par0plus, par0minus ]
spec:
  name: photosynthetically active radiation
---
apiVersion: extensions/sensing
kind: ObservedProperties
spec:
  name: transmission
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  ObservedProperties@iot.navigation:
    - name: [ transmission, cdom, cholorophyll ]
spec:
  name: turbidity
---
apiVersion: extensions/sensing
kind: ObservedProperties
spec:
  name: voltage
  description: Electrical voltage or sensor or power source
---
apiVersion: extensions/sensing
kind: ObservedProperties
metadata:
  Providers@iot.navigation:
     - label: Alias
       props:
         name: [ uv, u, ww, omega, current_speed_cm, current_direction ]
spec:
  name: water velocity
---
kind: Providers
metadata:
  owner: true
spec:
  name: Oceanicsdotio
  description: Research and development
  domain: oceanics.io
---
kind: Providers
spec:
  name: Public
  description: Public Data Repository
---
kind: Providers
spec:
  name: University of Maine
  description: Aquaculture research
  domain: maine.edu
---
apiVersion: extensions/sensing
kind: Sensors
spec:
  name: SeaBird Electronics CTD
  description: A common oceanographic sensing package
---
apiVersion: extensions/sensing
kind: Sensors
spec:
  name: Chlorophyll fluorometer
  description: For measuring plankton stuff
---
apiVersion: extensions/sensing
kind: Sensors
metadata:
  Things@iot.navigation:
     - name: [ Landsat-7 ]
spec:
  name: OLI
  description: Operational land imager
---
apiVersion: extensions/sensing
kind: Sensors
metadata:
  Things@iot.navigation:
     - name: [ Landsat-7 ]
spec:
  name: TIRS
  description: Thermal imaging radar on Landsat
---
apiVersion: extensions/sensing
kind: Things
metadata:
  Locations@iot.navigation:
     - id: [ 0 ]
spec:
  name: Land Ocean Biogeochemical Observatory
  description: Moored bathysphere_functions_buoy deployment of the Sustainable Ecological Aquaculture Network
---
apiVersion: extensions/sensing
kind: Things
spec:
  name: Landsat-7
  description: Satellite mission