---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: bathysphere
  labels:
    name: bathysphere
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphdb-pvc
  namespace: bathysphere
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bathysphere
  namespace: bathysphere
spec:
  rules:
    - host: db.oceanics.io
      http:
        paths:
          - path: /browser
            backend:
              serviceName: bathysphere-graph-neo4j
              servicePort: 7474

          - path: /neo4j
            backend:
              serviceName: bathysphere-graph-neo4j
              servicePort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: bathysphere-graph-neo4j
  namespace: bathysphere
spec:
  selector:
    name: bathysphere-graph-neo4j
  ports:
  - port: 7474
    targetPort: 7474
    protocol: TCP
    name: http
  - port: 7473
    targetPort: 7473
    protocol: TCP
    name: https
  - port: 7687
    targetPort: 7687
    protocol: TCP
    name: bolt
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bathysphere-graph-neo4j
  namespace: bathysphere
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bathysphere-graph-neo4j
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bathysphere-graph-neo4j
  namespace: bathysphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bathysphere-graph-neo4j

  template:
    metadata:
      name: bathysphere-graph-neo4j
      namespace: bathysphere
      labels:
        app: bathysphere-graph-neo4j

    spec:
      restartPolicy: Always

      containers:
        - name: neo4j
          image: oceanicsdotio/neo4j
          env:
            - name: NEO4J_dbms_security_auth__max__failed__attempts
              value: "6"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "100M"
            - name: NEO4J_dbms_memory_heap_maxSize
              value: "200M"
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
          volumeMounts:
            - name: graph-database
              mountPath: /data
            - name: plugins
              mountPath: /plugins

        - name: bathysphere-graph
          image: nginx
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: bathysphere-graph-secret-1
                  key: NEO4J_AUTH
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets/neo4j
              readOnly: true

      volumes:

        - name: secrets-volume
          secret:
            secretName: bathysphere-graph

        - name: graph-database
          persistentVolumeClaim:
            claimName: graphdb-pvc