name: bathysphere-array
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pytz
  - numpy
  - matplotlib
  - pandas
  - pyshp
  - pyproj
  - netCDF4
  - scipy
  - requests
  - pillow
  - scikit-learn
  - pip:
      - rdp
      - minio