monoPaths:
  - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono"
  - "/usr/bin/mono"
exePath: "/bin/kernel.exe"
logging: "logs/{}"
basePath: "/api"
specPath: "openapi/api.yml"
join:
  - bathysphere-graph
  - graph

graph: "bathysphere-graph:5000"
graphUser: ""
graphPassword: ""
graphApiKey: ""
graphHealthcheck: "http://{}/api/Things"
graphAuth: "http://{}/api/auth"
enableSwagger: false
configPattern: "config-{}"

lock: "lock.json"
index: "index.json"
bucketName: "oceanicsdotio"
storageAccessKey: ""
storageSecretKey: ""
storage:
  endpoint: "nyc3.digitaloceanspaces.com"
  secure: true

headers:
  x-amz-acl: "public-read"
  x-amz-meta-service: "neritics-bivalve"

configTemplate:
  metadata:
    name: "test-configuration"
    description: "A test configuration"
    keywords:
      - test
      - shellfish
    license: "No restrictions"

  properties:
    runs: 4
    workers: 2
    dt: 3600
    days: 30
    integration: "euler"
    backend: "shellsim"