shell:
  cavity_water_correction: 1.485
  energy_content: 1.035
  water_content: 0.048
  length:
    coefficient: 2.654
    exponent: 0.335
    maturation: 2.0
  
tissue:
  water_content: 0.804
  mean_allocation: 0.68
  proportion_dry_loss_to_spawn: 0.18

thermodynamics:
  heat_loss_coefficient: 0.074
  spawning_threshold: 13.0

ammonium_excretion: 
  max: 1250.0