logging: "logs/{}"
basePath: "/api"
specPath: "openapi/api.yml"
join:
  - bathysphere-graph
  - graph

graph: "bathysphere-graph:5000"
graphUser: ""
graphPassword: ""
graphApiKey: ""
graphHealthcheck: "http://{}/api/Things"
graphAuth: "http://{}/api/auth"
enableSwagger: false
configPattern: "config-{}"

lock: "lock.json"
index: "index.json"
bucketName: "oceanicsdotio"
storageAccessKey: ""
storageSecretKey: ""
storage:
  endpoint: "nyc3.digitaloceanspaces.com"
  secure: true

headers:
  x-amz-acl: "public-read"
  x-amz-meta-service: "neritics-bivalve"

configTemplate:
  metadata:
    name: "test-configuration"
    description: "A test configuration"
    keywords:
      - test
      - shellfish
    license: "No restrictions"

  properties:
    runs: 4
    workers: 2
    dt: 3600
    days: 30
    integration: "euler"
    backend: "shellsim"

imageStyles:
    base:
        padding: [0.1, 0.2, 0.05, 0.1]
        marker: 1
        font: 10
        text: 10
        width: 6.5
        height: 4.0
        line: 1.0
        alpha: 1.0
        dpi: 150
        legend: false
        grid: false
        imageInterp: bilinear
    
    dark:
        bg: black
        contrast: white
        flag: red
        label: white
        colors: [purple, blue, red, grey, green, yellow, orange, brown]
    
    light:
        bg: white
        contrast: black
        flag: red
        label: black
        colors: [purple, blue, red, grey, green, yellow, orange, brown]
    