name: bathysphere_graph
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip=18.1
  - neo4j-python-driver=1.6.2
  - pip:
    - connexion=2.2.0
    - flask=1.0.2
    - gunicorn=19.9.0
    - flask_cors=3.0.7
    - pytest=4.3.1
    - pytest_dependency=0.4.0
    - itsdangerous=1.1.0
    - passlib=1.7.1