- name: cdom
- name: chlorophyll
- name: conductivity
- name: current_direction
- name: current_speed_cm
- name: depth
- name: oxygen
- name: nitrate
- name: oxygen_sat
- name: oxygen_percent
- name: par0minus
- name: par0plus
- name: salinity
- name: temperature
- name: transmission
- name: turbidity
- name: voltage