config:
    sample_period: 5
    pole: single
    throw: double
    normally: open
    port: 2101
    timer_id_offset: 50
    buffer_size: 80    # tcp/ip message size/separation
    start: 254         # relay board command that starts each message


diagnostic:
    board: 50
    banks: 140
    current_bank: 34
    test: 33
    success: 85
    error: 1
    # get_refresh: 36
    status: 16         # get status


tasks:
    on: 48
    off: 47
    # timer_setup: 50
    # refresh_store: 35
    # reporting_on: 27
    # reporting_off: 28
    recover: 47
    # invert: 31
    # reverse: 32
    # refresh: 37
    # set_state: 40
    # set_startup: 42
    # refresh_on: 25     #
    # refresh_off: 26
    all_off: 29  # turn all relays in bank off
    all_on: 30  # turn all relays in bank on
    set_bank: 49  # change currently selected bank