- name: NECOFS data
  service: "thredds/dodsC/models/fvcom/NECOFS/Archive/Seaplan_33_Hindcast_v1"
  protocol: "http"
  hosts:
   - "www.smast.umassd.edu"
  port: 8080
  target: "gom3_{}.nc"
  format: NetCDF

- name: University of Maine Satellite Data
  hosts:
    - "misclab.umeoce.maine.edu"
  protocol: "ftp"
  service: "users/misclab/coastal_sat"
  target: "LC8011030JulyAvLGN00_OSI.nc"
  format: NetCDF
  port: 80

- name: S3 Storage
  hosts:
    - "bathysphere_minio"
    - "minio"
    - "localhost"
  port: 9000
  format: Binary


- name: Graph API
  hosts:
    - "localhost"
  port: 5000
  service: "api"
  protocol: https
  format: JSON

- name: National Oceanography Data Center
  host: "https://data.nodc.noaa.gov/"

- name: Other
  assets:
    - f"http://data.nodc.noaa.gov/thredds/dodsC/pathfinder/Version5.3/L3C/{filename[0:4]}/data/{filename}"
    - "20170709140704-NCEI-L3C_GHRSST-SSTskin-AVHRR_Pathfinder-PFV5.3_NOAA19_G_2017190_day-v02.0-fv01.0.nc"
    - "LC08_L1TP_011030_20170709_20170717_01_T1_B10.tif"

- service: "cgi-data/nph-data.cgi"
  protocol: "http"
  subdomain: "maine"
  home: "loboviz.com"
  admin: "info.html"
  data: "archive"
  metadata: "ingestorxml"
