- name: "Wood Island Harbor"
  identity: 64
  location: [43.456550, -70.344432]
  
- name: "Lower Damariscotta"
  identity: 65
  location: [43.93354, -69.58344]

- name: "Upper Damariscotta Estuary"
  identity: 66
  location: [43.998178, -69.54253]

- name: "Ram Island Saco Bay"
  identity: 67
  location: [43.465934, -70.359646]

- name: "Upper New Meadows"
  identity: 70
  location: [43.863669, -69.8984055]  # Bombazine / New Meadows

- name: "Lower New Meadows"
  identity: 71
  location: [43.77643055, -69.89196944]  # Sand Cove / New Meadows

- name: "Bagaduce River"
  identity: 72
  location: [44.40156667, -68.7738333]

- name: "Machias Bay"
  identity: 73
  location: [44.618517, -67.318033]

- name: "Cobscook Bay"
  identity: 74
  location: [44.8968, -67.0651]

- name: "Western Passage / Passamaquoddy Bay"
  identity: 75
  location: [44.92017, -66.995833]

- name: "Harpswell Sound"
  identity: 52

