spatial_points:
  view: spatial
  artifact: test_function_image_spatial_random_points
  data: 
    FeatureCollection:
      shape: [10, 4]
  
  style: 
    base: dark 
    alpha: 0.5 
    marker: 5
   
spatial_triangles: 
  view: spatial
  artifact: test_function_image_spatial_random_triangles
  data: 
    points:
      shape: [3, 4]
  style: 
    base: dark 
    alpha: 0.5
  

spatial_water_shapes: 
  view: spatial
  artifact: test_render_shapes_water
  style: 
    base: dark 
    alpha: 0.5 
    transparent: True
  
  data: 
    objectKey: bivalve-suitability/shapes-water
    

spatial_extent_culling: 
  view: spatial
  artifact: spatial_extent_culling
  data: 
    FeatureCollection: 
      features: 
        - objectKey: bivalve-suitability/shapes-water
          type: shape
          args: 
            edgecolor: blue
            facecolor: none
            sequential: True
            alpha: 0.5
        
      
        - objectKey: bivalve-suitability/extents-iter-1
          type: bbox
          args: 
            edgecolor: red
            facecolor: none
            sequential: True
            alpha: 0.25
        
      
        - objectKey: bivalve-suitability/convex-hulls-2
          type: shape
          args: 
            edgecolor: green
            facecolor: none
            alpha: 0.25
          
      
        - objectKey: bivalve-suitability/vertex-array-closures
          type: points
          args: 
            sequential: True
            alpha: 0.02
            m: 0.05
    
spatial_overlapping_shapes: 
  view: spatial
  artifact: test-render-osi-overlapping-shapes
  data: 
    FeatureCollection: 
      features: 
        - objectKey: bivalve-suitability/shapes-water-hole
          args: 
            stack: True
            limit: 3
            edgecolor: red
            facecolor: none
            transparent: True
            alpha: 0.5
            
        
        - objectKey: bivalve-suitability/shapes-water
          args: 
            stack: True
            limit: 23
            edgecolor: red
            facecolor: none
            transparent: True
            alpha: 0.5
          