version: "3.6"

networks:

  bathysphere:
    driver: bridge

services:

  # Approximately equivalent to the Aura DBaaS service we now use. 
  neo4j:
    image: neo4j:4.2.5
    ports:
      - 7474:7474 # http
      - 7473:7473 # https
      - 7687:7687 # bolt
    networks:
      - bathysphere
    environment:
      - NEO4J_AUTH=neo4j/n0t_p@55w0rd

  # Graph data access layer for testing.
  bathysphere:
    build:
      context: .
      dockerfile: Dockerfile
    image: oceanicsdotio/bathysphere
    ports:
      - 8080:8080
    networks:
      - bathysphere
    environment:
      - NEO4J_HOSTNAME=bathysphere_neo4j_1  # replaces localhost in Docker networking setup
      - NEO4J_ACCESS_KEY=n0t_p@55w0rd  # match value declared in neo4j above
    depends_on: 
      - neo4j