openapi: "3.0.0"

info:

  title: "Capsize Lexicon API"
  version: "0.2"
  description: |

    Some stuff

  contact:
    name: Oceanicsdotio
    url: http://www.oceanics.io
    email: business@oceanics.io

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

externalDocs:

  description: See the capsize repository for more information
  url: https://github.com/oceanicsdotio/capsize

x-tagGroups:

  - name: CAPSIZE API
    tags: [ Lexicon ]

tags:

  - name: Lexicon
    x-displayName: Lexicon
    description: |
      Natural language processing


servers:
- url: https://capsize.oceanics.io/{basePath}
  description: Production API server
  variables:
    basePath:
      default: api/lexicon

paths:

  /:

    get:

      tags: [Lexicon]
      operationId: capsize.lexicon.functions.lexicon
      summary: Lexicon
      description: |
        Look up a word or phrase
      parameters:
        - name: word
          in: query
          schema:
            type: string
        
        - name: mutations
          in: query
          schema:
            type: integer

      responses:
        '200':
          description: Lexicon
  