name: Build and Deploy

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
        name: Install Rust
      - run: make install-wasm-pack
        name: Install wasm-pack
      - run: make www-postcommit
        name: Make Postcommit