name: Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 16
          cache: 'yarn'

      - name: Configure Rust cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        
      - name: Restore wasm-pack
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack
        
      - name: Prepare API files
        run: make oceanics-io-wasm-node

      - name: Prepare WWW files
        run: make oceanics-io-wasm-www

      - name: Install Node dependencies (mock)
        run: mkdir .yarn/cache
        # run: yarn install --immutable

      # - run: make api-compile
      #   name: Build API

      # - name: Build WWW
      #   run: make www-compile
      