name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
      # Checkout repository using default action
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - id: cache
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install pytest pytest-cov
          pip install -e .
          pip install -r requirements.txt

      - name: Generate docs
        run: pdoc --html --force --output-dir static/bathysphere/docs bathysphere

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add
          git commit -m "Autogen Docs" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}