name: bathysphere-test

on:
  [push]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install -e .
        pipenv install --dev
  
    - name: Test with pytest
      run: |
        pipenv shell
        $(bathysphere test --kw=test_graph)