name: Neritics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
          
      - name: Pytest localhost
        run: |
          pipenv run test
        env:
          SPACES_SECRET: ${{ secrets.SPACES_SECRET }}
          SPACES_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_KEY }}
          STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
