name: Build

on:
  pull_request:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 16
          cache: 'yarn'

      - name: Configure Next cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/oceanics-io-www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('./yarn.lock') }}

      - name: Configure Rust cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        
      - name: Install wasm-pack
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack

      - name: Install and build dependencies
        run: make .  
      
      - name: Bundle site and API for Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify link --id $NETLIFY_SITE_ID && \
          yarn run netlify build

      - name: Deploy site to Netlify
        run: yarn run netlify deploy --prod
