name: Build

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  lock:
    name: Lock dependencies
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hash lockfile
        id: lockfile
        run: echo "::set-output name=hash::${{ hashFiles('./yarn.lock') }}"

      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 18
          cache: 'yarn'

      - name: Configure Next cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/oceanics-io-www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}
          restore-keys: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}

      - name: Configure Rust cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        
      - name: Install wasm-pack
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack

      - name: Update lockfile
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: make node_modules

      - name: Hash lockfile
        id: hash-lockfile
        run: echo "::set-output name=hash::${{ hashFiles('./yarn.lock') }}"

      - name: Commit lockfile
        if: steps.hash-lockfile.outputs.hash != steps.lockfile.outputs.hash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}
          git add yarn.lock
          git commit -m "Lockfile change"
          git push origin HEAD:${GITHUB_REF##*/}
        

  build:
    name: Build site
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    env:
      SERVICE_PROVIDER_API_KEY: ${{ secrets.SERVICE_PROVIDER_API_KEY }}
      SERVICE_ACCOUNT_USERNAME: ${{ secrets.SERVICE_ACCOUNT_USERNAME }}
      SERVICE_ACCOUNT_PASSWORD: ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
      SERVICE_ACCOUNT_SECRET: ${{ secrets.SERVICE_ACCOUNT_SECRET }}
      LOGTAIL_SOURCE_TOKEN: ${{ secrets.LOGTAIL_SOURCE_TOKEN }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hash lockfile
        id: lockfile
        run: echo "::set-output name=hash::${{ hashFiles('./yarn.lock') }}"

      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 18
          cache: 'yarn'

      - name: Configure Next cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/oceanics-io-www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}
          restore-keys: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}

      - name: Configure Rust cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        
      - name: Install wasm-pack
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack

      - name: Build all dependencies
        run: make .

      - name: Run dev server
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          NEO4J_HOSTNAME: ${{ secrets.NEO4J_HOSTNAME }}
          NEO4J_ACCESS_KEY: ${{ secrets.NEO4J_ACCESS_KEY }}
        run: make dev &

      - name: Test auth
        run: make test-auth

      - name: Test collections
        run: make test-collection

      - name: Test idempotent
        run: make test-idempotent
