name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/build-env.yaml

      - name: Install and build dependencies
        run: make .  
      
      - name: Bundle site and API for Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: yarn run netlify init && yarn run netlify build

      - name: Deploy site to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: yarn run netlify deploy --prod
