name: Build

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  lock:
    name: Lock dependencies
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hash lockfile
        id: lockfile
        run: echo "::set-output name=hash::${{ hashFiles('./yarn.lock') }}"

      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 16
          cache: 'yarn'

      - name: Configure Next cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/oceanics-io-www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}
          restore-keys: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}

      - name: Configure Rust cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        
      - name: Install wasm-pack
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack

      - name: Build yarn dependencies
        run: make node_modules  

      - name: Update lockfile
        id: update-lockfile
        run: |
          yarn install --mode update-lockfile
          echo "::set-output name=hash::${{ hashFiles('./yarn.lock') }}"

      - name: Commit lockfile
        if: steps.update-lockfile.outputs.hash != steps.lockfile.outputs.hash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit -m "Lockfile change"
          git push
        

  build:
    name: Build site
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hash lockfile
        id: lockfile
        run: echo "::set-output name=hash::${{ hashFiles('./yarn.lock') }}"

      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 16
          cache: 'yarn'

      - name: Configure Next cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/oceanics-io-www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}
          restore-keys: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}

      - name: Configure Rust cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        
      - name: Install wasm-pack
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack

      - name: Build all dependencies
        run: make .

      - name: Run dev server
        run: yarn netlify dev &

      - name: Test API
        run: |
          sleep 10s
          yarn workspace oceanics-io-api jest 
