name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hash lockfile
        id: lockfile
        run: echo "hash=${{ hashFiles('./yarn.lock') }}" >> $GITHUB_OUTPUT
      
      - uses: actions/setup-node@v3
        name: Configure Node cache
        id: node-cache
        with:
          node-version: 18
          cache: 'yarn'

      - name: Configure Next cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/oceanics-io-www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}
          restore-keys: ${{ runner.os }}-nextjs-${{ steps.lockfile.outputs.hash }}
        
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install and build dependencies
        run: make .  
      
      - name: Bundle site and API for Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: make netlify

      - name: Deploy site to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: make deploy
