name: Build

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2
        name: Configure Rust cache
        with:
          workspaces: 'rust'

      - uses: actions/setup-node@v4
        name: Configure Node
        with:
          node-version: 20

      - name: Build all dependencies
        env:
            YARN_ENABLE_IMMUTABLE_INSTALLS: false
            YARN_ENABLE_HARDENED_MODE: 0
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: make out
