name: Build

on:
  pull_request:
   
jobs:
  lock:
    name: Lock after dependency change
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/build-env.yaml

      - name: Yarn lock
        run: echo "placeholder"  

  build:
    name: Build site
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/build-env.yaml

      - name: Install and build dependencies
        run: make .  
