name: Test API

on:
  pull_request:
    branches: [ main ]
   
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: oceanics-io-api
        run: |
          pip install pytest pytest-cov
          pip install -e .
          pip install -r requirements.txt

      - name: Pytest against cloud database
        run: $(bathysphere test --kw=test_graph)
        env:
          NEO4J_ACCESS_KEY: ${{ secrets.NEO4J_ACCESS_KEY }}
          NEO4J_HOSTNAME: ${{ secrets.NEO4J_HOSTNAME }}
          SPACES_SECRET_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          SPACES_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_KEY }}
          SERVICE_ACCOUNT_USERNAME: ${{ secrets.SERVICE_ACCOUNT_USERNAME }}
          SERVICE_ACCOUNT_PASSWORD: ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
          SERVICE_ACCOUNT_SECRET: ${{ secrets.SERVICE_ACCOUNT_SECRET }}
          STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}