name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository using default action
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          pip install -e .
          pip install -r requirements.txt

      - name: Pytest against cloud database
        run: $(bathysphere test)
        env:
          NEO4J_ACCESS_KEY: ${{ secrets.NEO4J_ACCESS_KEY }}
          NEO4J_HOSTNAME: ${{ secrets.NEO4J_HOSTNAME }}
          SPACES_SECRET_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          SPACES_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_KEY }}
          STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}